name: build

on: 
  push:
    branches: 
      - master
    tags:
      - "Ver.*"

jobs:
  get_rev_list_count:
    name: Get rev-list_count
    runs-on: ubuntu-latest
    outputs:
      rev_list_count: ${{ steps.rev.outputs.REV_LIST_COUNT }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set REV_LIST_COUNT
      id: rev
      run: |
        cd ${{ github.workspace }}
        REVCOUNT=`git rev-list --count HEAD`
        echo "::set-output name=REV_LIST_COUNT::${REVCOUNT}"
    
  create_release:
    name: Create release
    runs-on: windows-latest
    needs: get_rev_list_count
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      upload_url2: ${{ steps.create_release2.outputs.upload_url }}
    steps:
    - name: Create a Release(Pre)
      if: (startsWith(github.ref, 'refs/tags/Ver')) != true
      id: create_release
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: prerelease-${{ needs.get_rev_list_count.outputs.rev_list_count }}
        release_name: TJAPlayer3-f-prerelease-${{ needs.get_rev_list_count.outputs.rev_list_count }}
        draft: false
        prerelease: true
    - name: Create a Release
      if: (startsWith(github.ref, 'refs/tags/Ver'))
      id: create_release2
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false
     
  build:
    name: Build
    runs-on: windows-latest
    needs: [create_release,get_rev_list_count]
    strategy:
      matrix:
        platform: [win-x86, win-x64, linux-x64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish TJAPlayer3 -o Test/net5.0 -r ${{matrix.platform}} -p:MyOption=PUBLISH -p:PublishSingleFile=true --configuration Release --self-contained true
    - name: Remove File
      uses: JesseTG/rm@v1.0.0
      with:
        path: Test/net5.0/${{matrix.platform}}
        
    - name: Rename App File
      if: matrix.platform == 'linux-x64'
      run: |
        cd $Env:GITHUB_WORKSPACE
        move "Test\net5.0\TJAPlayer3-f" "Test\net5.0\TJAPlayer3-f.AppImage"
        
    - name: Create Archive
      run: |
        cd $Env:GITHUB_WORKSPACE
        tar -a -cvf TJAPlayer3-f-Release.zip -C Test *
    
    #Push
    - name: Upload Release Asset(Pre)
      if: (startsWith(github.ref, 'refs/tags/Ver')) != true
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./TJAPlayer3-f-Release.zip
        asset_name: TJAPlayer3-f-PreRelease-${{matrix.platform}}-${{ needs.get_rev_list_count.outputs.rev_list_count }}.zip
        asset_content_type: application/zip

    #Release
    - name: Upload Release Asset
      if: (startsWith(github.ref, 'refs/tags/Ver'))
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url2 }}
        asset_path: ./TJAPlayer3-f-Release.zip
        asset_name: TJAPlayer3-f-${{matrix.platform}}-${{ github.ref }}.zip
        asset_content_type: application/zip
